New favicon
hackclub/ham-club pull request #7
Opened 2024-04-30 11:16 UTC by crnicholson

2024-04-30 12:07 UTC, jaspermayone requested changes

2024-04-30 12:07 UTC, jaspermayone commented on .gitignore
> +.github
@crnicholson this should not be in the gitignore.

2024-04-30 12:07 UTC, jaspermayone commented on README.md
> +# Development
do we need a development section

2024-04-30 12:07 UTC, jaspermayone commented on README.md
> +The Blot editor is run with an Express server.
We aren't blot

2024-04-30 12:07 UTC, jaspermayone commented on components/head.js
> +      <title>{title}</title>
there's super weird formatting here!

2024-04-30 12:07 UTC, jaspermayone commented on public/ham1.jpg
Why do we need these hams?

2024-04-30 12:07 UTC, jaspermayone commented on public/ham2.jpg
Why do we need these hams?

2024-04-30 12:07 UTC, jaspermayone commented on yarn.lock
We aren't using yarn, please don't check this in.

2024-04-30 12:07 UTC, jaspermayone commented on README.md
> +yarn dev
we use npm not yarn

2024-04-30 12:07 UTC, jaspermayone commented on README.md
> +yarn install
we use npm not yarn

2024-04-30 12:07 UTC, jaspermayone commented on README.md
> +After installing `Git`, `Node.js`, and `Yarn`, clone the repo.
we use npm not yarn

2024-05-01 01:22 UTC, crnicholson commented on components/head.js
> +      <title>{title}</title>
It was similar earlier

2024-05-01 02:00 UTC, jaspermayone commented
@crnicholson will re review shortly

2024-05-02 13:38 UTC, jaspermayone requested changes
@crnicholson please go through and make sure you addressed all the comments I made in my last review, then re request it once you have.

2024-05-02 22:47 UTC, closed without merging